// Copyright 2026 BitWise Media Group Ltd
// SPDX-License-Identifier: MIT

package report

import (
	"fmt"
	"os"
	"path/filepath"
	"sort"

	"github.com/bitwise-media-group/evolve/internal/layout"
	"github.com/bitwise-media-group/evolve/internal/provider"
	"github.com/bitwise-media-group/evolve/internal/results"
)

const generatedMarker = "<!-- Generated by evolve; do not edit by hand. Regenerate with: evolve report -->"

const methodology = `Input-token figures come from each provider's official token-counting API over
the skill's SKILL.md plus the query/prompt — the marginal context a triggering
eval loads — priced at the model's input rate at run time. Measured usage is
the harness-reported consumption of live case sessions (input includes cache
writes/reads). Cells show "—" when a figure has not been measured yet and
"n/a" when the provider cannot produce it (no counting API, no usage
reporting, or no published pricing).`

// Options configures report generation.
type Options struct {
	Repo        *layout.Repo
	ToolVersion string
	Providers   []provider.Provider // effective registry: display names + capabilities
	Format      string              // rollup format: json, jsonc, or yaml ("" = json)

	// ActiveModels, when non-nil, restricts the report to these "provider/model-id"
	// keys (a configured default_models). Entries for any other model are dropped
	// from the tables and listed in the "Excluded models" note. Nil means no
	// filtering — every model with stored results is reported.
	ActiveModels map[string]bool
}

// Summary is the machine-readable rollup written to EVALUATION.<format>.
type Summary struct {
	Schema      int                       `json:"schema"`
	ToolVersion string                    `json:"tool_version"`
	LatestRun   string                    `json:"latest_run,omitempty"`
	Plugins     map[string]*PluginSummary `json:"plugins"`
}

// PluginSummary aggregates one plugin's results per model key.
type PluginSummary struct {
	Triggers map[string]*ModelRollup `json:"triggers,omitempty"`
	Evals    map[string]*ModelRollup `json:"evals,omitempty"`
}

// ModelRollup aggregates one model's results across a plugin's skills.
type ModelRollup struct {
	Provider      string            `json:"provider"`
	Display       string            `json:"display"`
	Passed        *int              `json:"passed,omitempty"`
	Failed        *int              `json:"failed,omitempty"`
	Errored       *int              `json:"errored,omitempty"`
	Total         int               `json:"total"`
	PassRate      *float64          `json:"pass_rate,omitempty"`
	AvgRunSeconds *float64          `json:"avg_run_seconds,omitempty"`
	Estimate      *results.Estimate `json:"estimate,omitempty"`
	Measured      *results.Measured `json:"measured,omitempty"`

	priced    bool // any contributing entry snapshotted pricing
	executed  int  // total results across executed entries
	latestRun string
}

// pluginFiles is one plugin's loaded results, ordered by skill.
type pluginFiles struct {
	plugin layout.Plugin
	files  []*results.File
}

// Generate writes the reports and returns the summary for threshold checks.
func Generate(opts Options) (*Summary, error) {
	loaded, err := load(opts.Repo)
	if err != nil {
		return nil, err
	}
	caps := capabilities(opts.Providers)

	// When default_models is configured, drop non-active models from the tables
	// and surface the excluded set in a note at the top of the report.
	var excluded []excludedProvider
	if opts.ActiveModels != nil {
		filterActive(loaded, opts.ActiveModels)
		excluded = excludedModels(opts.Providers, opts.ActiveModels)
	}

	summary := &Summary{Schema: 2, ToolVersion: opts.ToolVersion, Plugins: map[string]*PluginSummary{}}
	for _, pf := range loaded {
		ps := &PluginSummary{
			Triggers: rollupTriggers(pf.files),
			Evals:    rollupEvals(pf.files),
		}
		if len(ps.Triggers) == 0 && len(ps.Evals) == 0 {
			continue
		}
		summary.Plugins[pf.plugin.Name] = ps
		for _, m := range ps.Triggers {
			summary.LatestRun = maxStr(summary.LatestRun, m.latestRun)
		}
		for _, m := range ps.Evals {
			summary.LatestRun = maxStr(summary.LatestRun, m.latestRun)
		}
	}

	root := renderRoot(opts, loaded, summary, caps, excluded)
	if err := writeFile(filepath.Join(opts.Repo.Root, "EVALUATION.md"), root); err != nil {
		return nil, err
	}
	if err := writeSummary(opts.Repo.Root, opts.Format, summary); err != nil {
		return nil, err
	}
	if opts.Repo.Kind != layout.Single {
		for _, pf := range loaded {
			if len(pf.files) == 0 {
				continue
			}
			page := renderDetailPage(pf, caps, "# "+pf.plugin.Name+" evaluations")
			if err := writeFile(filepath.Join(pf.plugin.Dir, "EVALUATION.md"), page); err != nil {
				return nil, err
			}
		}
	}
	return summary, nil
}

// Thresholds gate CI on minimum pass rates (config: report.thresholds).
type Thresholds struct {
	TriggersMinPassRate *float64
	EvalsMinPassRate    *float64
	Models              []string // model keys; empty = all models with results
}

// Check returns the breaches; an empty slice means the gate passes. A
// threshold model with no stored results is itself a breach — silent absence
// must not pass CI.
func Check(summary *Summary, th Thresholds) []string {
	type agg struct{ passed, executed int }
	totals := map[string]map[string]*agg{"triggers": {}, "evals": {}}
	for _, ps := range summary.Plugins {
		for kind, rollups := range map[string]map[string]*ModelRollup{"triggers": ps.Triggers, "evals": ps.Evals} {
			for key, m := range rollups {
				if m.Passed == nil {
					continue
				}
				a := totals[kind][key]
				if a == nil {
					a = &agg{}
					totals[kind][key] = a
				}
				a.passed += *m.Passed
				a.executed += m.executed
			}
		}
	}

	var breaches []string
	check := func(kind string, minRate *float64) {
		if minRate == nil {
			return
		}
		keys := th.Models
		if len(keys) == 0 {
			for key := range totals[kind] {
				keys = append(keys, key)
			}
			sort.Strings(keys)
		}
		for _, key := range keys {
			a := totals[kind][key]
			if a == nil || a.executed == 0 {
				breaches = append(breaches, fmt.Sprintf("%s: no stored results for %s", kind, key))
				continue
			}
			rate := float64(a.passed) / float64(a.executed)
			if rate < *minRate {
				breaches = append(breaches, fmt.Sprintf("%s: %s pass rate %.1f%% below threshold %.1f%%",
					kind, key, rate*100, *minRate*100))
			}
		}
	}
	check("triggers", th.TriggersMinPassRate)
	check("evals", th.EvalsMinPassRate)
	return breaches
}

func load(repo *layout.Repo) ([]pluginFiles, error) {
	sets, err := repo.EvalSets()
	if err != nil {
		return nil, err
	}
	byPlugin := map[string]*pluginFiles{}
	var order []string
	for _, set := range sets {
		if results.Find(set.ResultsDir) == "" {
			continue
		}
		pf := byPlugin[set.Plugin.Name]
		if pf == nil {
			pf = &pluginFiles{plugin: set.Plugin}
			byPlugin[set.Plugin.Name] = pf
			order = append(order, set.Plugin.Name)
		}
		file, _ := results.LoadDir(set.ResultsDir, set.Plugin.Name, set.Skill)
		pf.files = append(pf.files, file)
	}
	out := make([]pluginFiles, 0, len(order))
	for _, name := range order {
		out = append(out, *byPlugin[name])
	}
	return out, nil
}

// filterActive drops every trigger/eval entry whose model key is not in active.
// The loaded files are freshly read and unshared, so mutating them in place is
// safe and filters the rollups and the detail tables in one move.
func filterActive(loaded []pluginFiles, active map[string]bool) {
	for _, pf := range loaded {
		for _, f := range pf.files {
			for key := range f.Triggers {
				if !active[key] {
					delete(f.Triggers, key)
				}
			}
			for key := range f.Evals {
				if !active[key] {
					delete(f.Evals, key)
				}
			}
		}
	}
}

// excludedProvider is one provider's models that default_models excludes.
type excludedProvider struct {
	display string
	all     bool     // every one of the provider's models is excluded
	models  []string // excluded model ids (sorted), when not all
}

// excludedModels lists, per provider, the catalog models absent from active.
// It is catalog-driven (not results-driven) so the note stays stable whether or
// not stale results were dropped.
func excludedModels(providers []provider.Provider, active map[string]bool) []excludedProvider {
	var out []excludedProvider
	for _, p := range providers {
		var excl []string
		total := 0
		for _, m := range p.Models() {
			total++
			if !active[p.Name()+"/"+m.ID] {
				excl = append(excl, m.ID)
			}
		}
		if len(excl) == 0 {
			continue
		}
		sort.Strings(excl)
		out = append(out, excludedProvider{display: p.Display(), all: len(excl) == total, models: excl})
	}
	return out
}

type capabilityMap struct {
	counts  map[string]bool
	usage   map[string]bool
	display map[string]string
}

func capabilities(providers []provider.Provider) capabilityMap {
	caps := capabilityMap{counts: map[string]bool{}, usage: map[string]bool{}, display: map[string]string{}}
	for _, p := range providers {
		_, caps.counts[p.Name()] = p.(provider.TokenCounter)
		if cr, ok := p.(provider.EvalRunner); ok {
			caps.usage[p.Name()] = cr.ReportsUsage()
		}
		caps.display[p.Name()] = p.Display()
	}
	return caps
}

func (c capabilityMap) providerDisplay(name string) string {
	if d := c.display[name]; d != "" {
		return d
	}
	return name
}

func rollupTriggers(files []*results.File) map[string]*ModelRollup {
	rollups := map[string]*ModelRollup{}
	for _, f := range files {
		for key, entry := range f.Triggers {
			m := ensureRollup(rollups, key, entry.Header)
			m.Total += entry.Summary.Total
			if entry.Executed && entry.Summary.Passed != nil {
				addExecuted(m, *entry.Summary.Passed, entry.Summary.Total, entry.Summary.AvgRunSeconds)
			}
			m.Estimate = mergeEstimates(m.Estimate, entry.Summary.Estimate)
		}
	}
	finalize(rollups)
	return rollups
}

func rollupEvals(files []*results.File) map[string]*ModelRollup {
	rollups := map[string]*ModelRollup{}
	for _, f := range files {
		for key, entry := range f.Evals {
			m := ensureRollup(rollups, key, entry.Header)
			m.Total += entry.Summary.Total
			if entry.Executed && entry.Summary.Passed != nil {
				addExecuted(m, *entry.Summary.Passed, entry.Summary.Total, entry.Summary.AvgRunSeconds)
			}
			if entry.Summary.Errored != nil {
				if m.Errored == nil {
					m.Errored = new(int)
				}
				*m.Errored += *entry.Summary.Errored
			}
			m.Estimate = mergeEstimates(m.Estimate, entry.Summary.Estimate)
			m.Measured = mergeMeasured(m.Measured, entry.Summary.Measured)
		}
	}
	finalize(rollups)
	return rollups
}

func ensureRollup(rollups map[string]*ModelRollup, key string, h results.Header) *ModelRollup {
	m := rollups[key]
	if m == nil {
		m = &ModelRollup{Provider: h.Provider, Display: h.Display}
		rollups[key] = m
	}
	m.priced = m.priced || h.Pricing != nil
	m.latestRun = maxStr(m.latestRun, h.RanAt)
	return m
}

func addExecuted(m *ModelRollup, passed, total int, avg *float64) {
	if m.Passed == nil {
		m.Passed = new(int)
	}
	*m.Passed += passed
	// Weighted average run time accumulates as a sum here; finalize divides.
	if avg != nil {
		if m.AvgRunSeconds == nil {
			m.AvgRunSeconds = new(float64)
		}
		*m.AvgRunSeconds += *avg * float64(total)
	}
	m.executed += total
}

func finalize(rollups map[string]*ModelRollup) {
	for _, m := range rollups {
		if m.Passed != nil && m.executed > 0 {
			// Errored runs are excluded from the pass-rate and failed counts
			// (they never produced a gradable answer), but kept in the avg-run
			// weighting since they did consume wall-clock.
			errored := 0
			if m.Errored != nil {
				errored = *m.Errored
			}
			if graded := m.executed - errored; graded > 0 {
				failed := graded - *m.Passed
				m.Failed = &failed
				rate := results.Round6(float64(*m.Passed) / float64(graded))
				m.PassRate = &rate
			}
			if m.AvgRunSeconds != nil {
				avg := results.Round1(*m.AvgRunSeconds / float64(m.executed))
				m.AvgRunSeconds = &avg
			}
		}
	}
}

func mergeEstimates(a, b *results.Estimate) *results.Estimate {
	return results.SumEstimates([]*results.Estimate{a, b})
}

func mergeMeasured(a, b *results.Measured) *results.Measured {
	if a == nil {
		return b
	}
	if b == nil {
		return a
	}
	out := &results.Measured{}
	out.InputTokens = addInts(a.InputTokens, b.InputTokens)
	out.CacheReadTokens = addInts(a.CacheReadTokens, b.CacheReadTokens)
	out.CacheCreationTokens = addInts(a.CacheCreationTokens, b.CacheCreationTokens)
	out.OutputTokens = addInts(a.OutputTokens, b.OutputTokens)
	if a.CostUSD != nil || b.CostUSD != nil {
		var sum float64
		if a.CostUSD != nil {
			sum += *a.CostUSD
		}
		if b.CostUSD != nil {
			sum += *b.CostUSD
		}
		sum = results.Round6(sum)
		out.CostUSD = &sum
	}
	return out
}

func addInts(a, b *int) *int {
	if a == nil && b == nil {
		return nil
	}
	sum := 0
	if a != nil {
		sum += *a
	}
	if b != nil {
		sum += *b
	}
	return &sum
}

func sortedKeys[V any](m map[string]V) []string {
	keys := make([]string, 0, len(m))
	for k := range m {
		keys = append(keys, k)
	}
	sort.Strings(keys)
	return keys
}

func maxStr(a, b string) string {
	if b > a {
		return b
	}
	return a
}

func writeFile(path, content string) error {
	return os.WriteFile(path, []byte(content), 0o644)
}
