// Copyright 2026 BitWise Media Group Ltd
// SPDX-License-Identifier: MIT

package harness

import (
	"bufio"
	"bytes"
	"encoding/json"
	"os"
	"path/filepath"
	"strconv"
	"strings"
	"sync/atomic"

	"github.com/bitwise-media-group/evolve/internal/model"
)

// grokDefaultAllowedTools mirrors claudeDefaultAllowedTools as Claude-compatible
// --allow rules (Grok documents --allow as the Claude Code --allowedTools analog).
const grokDefaultAllowedTools = "Read Write Edit Glob Grep Skill Bash(terraform *) Bash(tflint *) Bash(mkdir *)"

// grokHomeRel is the workspace-relative GROK_HOME evolve gives the grok CLI.
// Sessions, config, and (later) hooks live here so trigger/eval runs do not
// touch the operator's real ~/.grok. Project skills stay at .grok/skills (the
// skillDirs mount); this directory is only agent state.
const grokHomeRel = ".evolve/grok-home"

// grokIsolatedConfig is written into the per-workspace GROK_HOME so the agent
// does not scan the operator's Claude/Cursor skills, hooks, rules, or MCP
// configs. Browser/session auth is shared from the operator home via a
// symlink to auth.json (see linkGrokAuth); API keys remain a CI fallback and
// the token-counting path.
const grokIsolatedConfig = `# Generated by evolve for an isolated grok harness run.
# Do not point interactive grok sessions at this directory.

[compat.cursor]
skills = false
hooks = false
rules = false
agents = false
mcps = false

[compat.claude]
skills = false
hooks = false
rules = false
agents = false
mcps = false
`

// grokTriggerHitHookJSON registers a PreToolUse hook that marks skill
// activation for trigger early-exit. The per-query needle and hit file come
// from EVOLVE_HIT_NEEDLE / EVOLVE_HIT_FILE on the agent process env (inherited
// by the hook child), so concurrent queries sharing one workspace stay isolated.
const grokTriggerHitHookJSON = `{
  "hooks": {
    "PreToolUse": [
      {
        "matcher": "Read|read_file",
        "hooks": [
          {
            "type": "command",
            "command": "./evolve-trigger-hit.sh",
            "timeout": 5
          }
        ]
      }
    ]
  }
}
`

// grokTriggerHitHookScript inspects the PreToolUse JSON on stdin. When the
// payload mentions EVOLVE_HIT_NEEDLE (skills/<skill>/SKILL.md), it creates
// EVOLVE_HIT_FILE so the evolve runner can cancel the agent early. Always
// allows the tool call — detection is passive.
const grokTriggerHitHookScript = `#!/bin/sh
# evolve: mark skill activation for trigger early-exit (PreToolUse).
needle="${EVOLVE_HIT_NEEDLE:-}"
hit="${EVOLVE_HIT_FILE:-}"
if [ -n "$needle" ] && [ -n "$hit" ]; then
  if grep -Fq -- "$needle"; then
    : >"$hit" 2>/dev/null || true
  fi
else
  cat >/dev/null
fi
printf '%s\n' '{"decision":"allow"}'
exit 0
`

// grokHitSeq allocates unique per-invocation hit-file names under a shared
// trigger workspace (jobs > 1).
var grokHitSeq atomic.Uint64

// Grok drives the `grok` CLI (Grok Build TUI).
type Grok struct {
	base
}

// NewGrok returns the builtin Grok harness.
func NewGrok() *Grok {
	return &Grok{base: base{
		id:   model.HarnessGrok,
		name: "Grok",
		clis: []string{"grok"},
		// Prefer interactive `grok login` credentials (auth.json linked into the
		// isolated home). EVOLVE_XAI_API_KEY / XAI_API_KEY are the CI fallback
		// and what the xAI token-counting client uses; doctor may report them
		// unset when only browser auth is configured.
		envKeys:   []string{"EVOLVE_XAI_API_KEY", "XAI_API_KEY"},
		skillDirs: []string{filepath.Join(".grok", "skills")},
	}}
}

// appendAllowRules expands a Claude-style tool grammar into repeated --allow
// flags Grok understands (e.g. "Read Bash(git *)" → --allow Read --allow
// Bash(git *)). Tokens are space-separated outside parentheses so patterns like
// Bash(terraform *) stay one rule.
func appendAllowRules(argv []string, tools string) []string {
	for _, rule := range splitAllowRules(tools) {
		argv = append(argv, "--allow", rule)
	}
	return argv
}

// splitAllowRules splits a Claude-style allowed-tools string on whitespace
// outside parentheses.
func splitAllowRules(tools string) []string {
	var rules []string
	var b strings.Builder
	depth := 0
	flush := func() {
		if s := strings.TrimSpace(b.String()); s != "" {
			rules = append(rules, s)
		}
		b.Reset()
	}
	for _, r := range tools {
		switch {
		case r == '(':
			depth++
			b.WriteRune(r)
		case r == ')':
			if depth > 0 {
				depth--
			}
			b.WriteRune(r)
		case r == ' ' || r == '\t' || r == '\n':
			if depth == 0 {
				flush()
			} else {
				b.WriteRune(r)
			}
		default:
			b.WriteRune(r)
		}
	}
	flush()
	return rules
}

// grokSandboxArg returns the --sandbox profile for this run. When evolve already
// confines the process (hostSandboxed), Grok's own Seatbelt/Landlock sandbox
// must be off — the two cannot nest. When evolve is unconfined, use workspace
// so Grok supplies write confinement analogous to Claude Code's Bash sandbox.
func grokSandboxArg(hostSandboxed bool) string {
	if hostSandboxed {
		return "off"
	}
	return "workspace"
}

// grokHomeDir is the absolute GROK_HOME for a workspace-rooted run.
func grokHomeDir(ws string) string {
	if ws == "" {
		return grokHomeRel
	}
	return filepath.Join(ws, filepath.FromSlash(grokHomeRel))
}

// operatorGrokHome is the operator's real Grok config root (source of browser
// auth), not the per-workspace isolated home. Honors GROK_HOME when the parent
// evolve process itself has it set; otherwise ~/.grok.
func operatorGrokHome() string {
	if h := os.Getenv("GROK_HOME"); h != "" {
		return h
	}
	userHome, err := os.UserHomeDir()
	if err != nil || userHome == "" {
		return ""
	}
	return filepath.Join(userHome, ".grok")
}

// ensureGrokHome creates the isolated home, seeds a minimal config.toml that
// disables foreign-harness skill/hook discovery, installs the trigger-hit hook,
// and links the operator's auth.json so browser/session login still works.
// Best-effort: a failure still leaves GROK_HOME set so the CLI can create the
// tree itself.
func ensureGrokHome(home string) {
	if err := os.MkdirAll(home, 0o755); err != nil {
		return
	}
	cfg := filepath.Join(home, "config.toml")
	if _, err := os.Stat(cfg); err != nil {
		_ = os.WriteFile(cfg, []byte(grokIsolatedConfig), 0o644)
	}
	seedGrokTriggerHitHook(home)
	linkGrokAuth(home)
}

// seedGrokTriggerHitHook writes the PreToolUse hook used for trigger early-exit
// under $GROK_HOME/hooks (global to this isolated home → always trusted).
func seedGrokTriggerHitHook(home string) {
	hooksDir := filepath.Join(home, "hooks")
	if err := os.MkdirAll(hooksDir, 0o755); err != nil {
		return
	}
	script := filepath.Join(hooksDir, "evolve-trigger-hit.sh")
	if err := os.WriteFile(script, []byte(grokTriggerHitHookScript), 0o755); err != nil {
		return
	}
	_ = os.WriteFile(filepath.Join(hooksDir, "evolve-trigger-hit.json"),
		[]byte(grokTriggerHitHookJSON), 0o644)
}

// ArmTriggerHit implements TriggerSideChannel. It creates a unique hit file and
// returns process env that the seeded PreToolUse hook reads. sideHit becomes
// true once the hook touches the file (skill SKILL.md read).
func (g *Grok) ArmTriggerHit(ws, skill string) (sideHit func() bool, env []string) {
	ensureGrokHome(grokHomeDir(ws))
	hitsDir := filepath.Join(ws, ".evolve", "hits")
	_ = os.MkdirAll(hitsDir, 0o755)
	hitFile := filepath.Join(hitsDir, strconv.FormatUint(grokHitSeq.Add(1), 10))
	// Remove a stale marker from a prior crash with the same seq (shouldn't
	// happen); ignore errors.
	_ = os.Remove(hitFile)
	needle := "skills/" + skill + "/SKILL.md"
	env = []string{
		"EVOLVE_HIT_FILE=" + hitFile,
		"EVOLVE_HIT_NEEDLE=" + needle,
	}
	sideHit = func() bool {
		_, err := os.Stat(hitFile)
		return err == nil
	}
	return sideHit, env
}

// linkGrokAuth exposes the operator's auth.json inside the isolated home.
// Prefers a symlink so mid-run token refresh writes through to the real
// credentials; falls back to a one-shot copy when symlink is unavailable.
// No-op when the operator has no auth.json (CI with API key only) or the
// destination already exists.
func linkGrokAuth(isolatedHome string) {
	srcHome := operatorGrokHome()
	if srcHome == "" || sameFilePath(srcHome, isolatedHome) {
		return
	}
	src := filepath.Join(srcHome, "auth.json")
	dst := filepath.Join(isolatedHome, "auth.json")
	if _, err := os.Lstat(dst); err == nil {
		return
	}
	if _, err := os.Stat(src); err != nil {
		return
	}
	if err := os.Symlink(src, dst); err == nil {
		return
	}
	data, err := os.ReadFile(src)
	if err != nil {
		return
	}
	_ = os.WriteFile(dst, data, 0o600)
}

// sameFilePath reports whether a and b name the same path after cleaning.
func sameFilePath(a, b string) bool {
	a, errA := filepath.Abs(a)
	b, errB := filepath.Abs(b)
	if errA != nil || errB != nil {
		return a == b
	}
	return a == b
}

// grokEnv returns the process env extras for a grok invocation in ws: isolated
// GROK_HOME plus env toggles that reinforce the seeded config.toml (env wins
// over remote defaults).
func grokEnv(ws string) []string {
	home := grokHomeDir(ws)
	ensureGrokHome(home)
	return []string{
		"GROK_HOME=" + home,
		"GROK_CLAUDE_SKILLS_ENABLED=false",
		"GROK_CURSOR_SKILLS_ENABLED=false",
		"GROK_DISABLE_AUTOUPDATER=1",
	}
}

func (g *Grok) TriggerSpec(ws, query, cliModelID string, hostSandboxed bool) model.CommandSpec {
	argv := []string{
		"grok", "-p", query,
		"--model", cliModelID,
		"--output-format", "streaming-json",
		"--max-turns", "2",
		"--disable-web-search",
		"--no-memory",
		"--sandbox", grokSandboxArg(hostSandboxed),
	}
	argv = appendAllowRules(argv, "Skill Read")
	return model.CommandSpec{Argv: argv, Dir: ws, Env: grokEnv(ws)}
}

func (g *Grok) EvalSpec(ws string, in model.EvalInput, cliModelID string) model.CommandSpec {
	maxTurns := in.MaxTurns
	if maxTurns == 0 {
		maxTurns = model.DefaultMaxTurns
	}
	tools := in.AllowedTools
	if tools == "" {
		tools = grokDefaultAllowedTools
	}
	argv := []string{
		"grok", "-p", in.Prompt,
		"--model", cliModelID,
		"--output-format", "json",
		"--max-turns", strconv.Itoa(maxTurns),
		"--disable-web-search",
		"--no-memory",
		"--sandbox", grokSandboxArg(in.HostSandboxed),
	}
	argv = appendAllowRules(argv, tools)
	return model.CommandSpec{Argv: argv, Dir: ws, Env: grokEnv(ws)}
}

// ScanLine detects skill activation for a trigger query.
//
// Headless --output-format streaming-json only documents text/thought/end/error
// (no tool events), so a path substring in the stream is rare. When the terminal
// end (or error) event carries a sessionId, ScanLine opens that session's
// updates.jsonl under the run's isolated GROK_HOME (workDir/.evolve/grok-home)
// and looks for a tool_call that touched skills/<skill>/SKILL.md — the same
// signal Cursor/Claude get from their structured tool streams. A direct path
// match on the line itself is still accepted as a fast path.
//
// workDir is the agent command's working directory (CommandSpec.Dir); other
// harnesses ignore it.
func (g *Grok) ScanLine(line []byte, skill, workDir string) (bool, string) {
	needle := "skills/" + skill + "/SKILL.md"
	if strings.Contains(string(line), needle) {
		return true, ""
	}
	var ev struct {
		Type      string `json:"type"`
		SessionID string `json:"sessionId"`
	}
	if json.Unmarshal(line, &ev) != nil {
		return false, ""
	}
	if (ev.Type != "end" && ev.Type != "error") || ev.SessionID == "" {
		return false, ""
	}
	return grokSessionSkillHit(ev.SessionID, needle, workDir), ""
}

// grokSessionSkillHit reports whether the named session's ACP updates stream
// records a tool_call (or tool_call_update) that references needle (the skill's
// SKILL.md path fragment). Sessions live at
// $GROK_HOME/sessions/<encoded-cwd>/<sessionId>/updates.jsonl; encoded-cwd is
// opaque so we glob one level. Missing sessions count as no-hit rather than
// error so trigger runs stay best-effort.
func grokSessionSkillHit(sessionID, needle, workDir string) bool {
	path, ok := grokSessionUpdatesPath(sessionID, workDir)
	if !ok {
		return false
	}
	f, err := os.Open(path)
	if err != nil {
		return false
	}
	defer f.Close()
	sc := bufio.NewScanner(f)
	// Session lines can carry full tool results; raise the token limit so a
	// large SKILL.md body does not skip the activation event.
	sc.Buffer(make([]byte, 0, 64*1024), 4<<20)
	for sc.Scan() {
		line := sc.Bytes()
		if !bytes.Contains(line, []byte(needle)) {
			continue
		}
		var row struct {
			Params struct {
				Update struct {
					SessionUpdate string `json:"sessionUpdate"`
				} `json:"update"`
			} `json:"params"`
		}
		if json.Unmarshal(line, &row) != nil {
			continue
		}
		switch row.Params.Update.SessionUpdate {
		case "tool_call", "tool_call_update":
			return true
		}
	}
	return false
}

// grokSessionUpdatesPath resolves updates.jsonl for sessionID. Search order:
// the workspace-isolated GROK_HOME (preferred), then GROK_HOME from the parent
// env, then ~/.grok (legacy / interactive). Returns ok=false when nothing
// matches or sessionID is unsafe.
func grokSessionUpdatesPath(sessionID, workDir string) (string, bool) {
	if sessionID == "" || strings.Contains(sessionID, string(filepath.Separator)) ||
		strings.Contains(sessionID, "..") {
		return "", false
	}
	var roots []string
	if workDir != "" {
		roots = append(roots, grokHomeDir(workDir))
	}
	if h := os.Getenv("GROK_HOME"); h != "" {
		roots = append(roots, h)
	}
	if userHome, err := os.UserHomeDir(); err == nil && userHome != "" {
		roots = append(roots, filepath.Join(userHome, ".grok"))
	}
	seen := make(map[string]bool, len(roots))
	for _, home := range roots {
		if home == "" || seen[home] {
			continue
		}
		seen[home] = true
		matches, err := filepath.Glob(filepath.Join(home, "sessions", "*", sessionID, "updates.jsonl"))
		if err == nil && len(matches) > 0 {
			return matches[0], true
		}
	}
	return "", false
}

// grokResult is the single JSON object emitted by `grok -p --output-format json`
// (and the terminal `end` event of streaming-json, which carries the same spend
// fields). See Grok headless-mode docs for the field policy: input_tokens is
// uncached only; cache hits live on cache_read_input_tokens.
type grokResult struct {
	Type         string   `json:"type"` // "error" on failure envelope
	Message      string   `json:"message"`
	Text         string   `json:"text"`
	StopReason   string   `json:"stopReason"`
	TotalCostUSD *float64 `json:"total_cost_usd"`
	Usage        *struct {
		InputTokens          int  `json:"input_tokens"`
		CacheReadInputTokens int  `json:"cache_read_input_tokens"`
		OutputTokens         *int `json:"output_tokens"`
	} `json:"usage"`
}

// ParseEvalOutput reads the final answer and usage from grok's JSON object.
// Non-JSON stdout falls back to the raw text with nil usage.
func (g *Grok) ParseEvalOutput(stdout []byte) (string, *model.Usage) {
	result, ok := parseGrokResult(stdout)
	if !ok {
		return string(stdout), nil
	}
	if result.Usage == nil {
		return result.Text, nil
	}
	in := result.Usage.InputTokens
	cacheRead := result.Usage.CacheReadInputTokens
	return result.Text, &model.Usage{
		InputTokens:     &in,
		CacheReadTokens: &cacheRead,
		OutputTokens:    result.Usage.OutputTokens,
		CostUSD:         result.TotalCostUSD,
	}
}

// ReportsUsage reports that the grok CLI reports session usage and cost in its
// JSON output.
func (g *Grok) ReportsUsage() bool { return true }

// RuntimeError detects a grok run that produced no usable answer (auth blocked,
// error envelope, empty output) so it is reported distinctly from a failed eval.
func (g *Grok) RuntimeError(stdout []byte, exitCode int, timedOut bool) string {
	if len(bytes.TrimSpace(stdout)) == 0 {
		return "empty CLI output"
	}
	result, ok := parseGrokResult(stdout)
	if !ok {
		if exitCode != 0 {
			return "unparseable CLI output"
		}
		return "" // clean exit with plain text is degenerate but gradable
	}
	if result.Type == "error" {
		msg := strings.TrimSpace(result.Message)
		if msg == "" {
			return "grok run error"
		}
		return "grok run error: " + msg
	}
	if result.Text != "" {
		return "" // there is an answer to grade
	}
	if exitCode != 0 {
		return "grok produced no answer"
	}
	return "" // empty-result success: grade it (assertions may inspect the workspace)
}

// parseGrokResult decodes a single JSON object from stdout, or the last
// parseable line of a streaming-json stream (preferring an end/error event).
func parseGrokResult(stdout []byte) (grokResult, bool) {
	trimmed := bytes.TrimSpace(stdout)
	if len(trimmed) == 0 {
		return grokResult{}, false
	}
	// Prefer a single-object decode (eval --output-format json).
	var single grokResult
	if json.Unmarshal(trimmed, &single) == nil && (single.Text != "" || single.Type != "" || single.Usage != nil || single.Message != "") {
		return single, true
	}
	// Fall back to the last meaningful event in a streaming-json stream.
	var last grokResult
	found := false
	for _, line := range bytes.Split(stdout, []byte{'\n'}) {
		line = bytes.TrimSpace(line)
		if len(line) == 0 {
			continue
		}
		var ev grokResult
		if json.Unmarshal(line, &ev) != nil {
			continue
		}
		if ev.Type == "end" || ev.Type == "error" || ev.Text != "" || ev.Usage != nil {
			last, found = ev, true
		}
	}
	return last, found
}
